package com.tema4.models;
//Generated 15 dic. 2020 17:38:37 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Films generated by hbm2java
 */
@Entity
@Table(name = "films")
public class Films implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	private int codigo;
	
	@Column(name = "title", length = 100)
	private String title;
	
	@Column(name = "episode_id", length = 100)
	private String episodeId;
	
	@Column(name = "opening_crawl", length = 10485760)
	private String openingCrawl;
	
	@Column(name = "director", length = 100)
	private String director;
	
	@Column(name = "producer", length = 100)
	private String producer;
	
	@Column(name = "release_date", length = 100)
	private String releaseDate;
	
	@Column(name = "created", length = 100)
	private String created;
	
	@Column(name = "edited", length = 100)
	private String edited;
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "starships_films", joinColumns = {
			@JoinColumn(name = "codigo_film", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_starship", nullable = false, updatable = false) })
	private Set<Starships> starships = new HashSet<Starships>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "films_planets", joinColumns = {
			@JoinColumn(name = "codigo_film", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_planet", nullable = false, updatable = false) })
	private Set<Planets> planets = new HashSet<Planets>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "films_people", joinColumns = {
			@JoinColumn(name = "codigo_film", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_people", nullable = false, updatable = false) })
	private Set<People> peoples = new HashSet<People>(0);
	
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "vehicles_films", joinColumns = {
			@JoinColumn(name = "codigo_film", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_vehicle", nullable = false, updatable = false) })
	private Set<Vehicles> vehicles = new HashSet<Vehicles>(0);

	public Films() {
	}

	public Films(int codigo) {
		this.codigo = codigo;
	}

	public Films(int codigo, String title, String episodeId, String openingCrawl, String director, String producer,
			String releaseDate, String created, String edited, Set<Starships> starships, Set<Planets> planets,
			Set<People> peoples, Set<Vehicles> vehicles) {
		this.codigo = codigo;
		this.title = title;
		this.episodeId = episodeId;
		this.openingCrawl = openingCrawl;
		this.director = director;
		this.producer = producer;
		this.releaseDate = releaseDate;
		this.created = created;
		this.edited = edited;
		this.starships = starships;
		this.planets = planets;
		this.peoples = peoples;
		this.vehicles = vehicles;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEpisodeId() {
		return episodeId;
	}

	public void setEpisodeId(String episodeId) {
		this.episodeId = episodeId;
	}

	public String getOpeningCrawl() {
		return openingCrawl;
	}

	public void setOpeningCrawl(String openingCrawl) {
		this.openingCrawl = openingCrawl;
	}

	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public String getProducer() {
		return producer;
	}

	public void setProducer(String producer) {
		this.producer = producer;
	}

	public String getReleaseDate() {
		return releaseDate;
	}

	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}

	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	public String getEdited() {
		return edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	public Set<Starships> getStarships() {
		return starships;
	}

	public void setStarships(Set<Starships> starships) {
		this.starships = starships;
	}

	public Set<Planets> getPlanets() {
		return planets;
	}

	public void setPlanets(Set<Planets> planets) {
		this.planets = planets;
	}

	public Set<People> getPeoples() {
		return peoples;
	}

	public void setPeoples(Set<People> peoples) {
		this.peoples = peoples;
	}

	public Set<Vehicles> getVehicles() {
		return vehicles;
	}

	public void setVehicles(Set<Vehicles> vehicles) {
		this.vehicles = vehicles;
	}

	@Override
	public String toString() {
		return "Films [codigo=" + codigo + ", title=" + title + ", episodeId=" + episodeId + ", openingCrawl="
				+ openingCrawl + ", director=" + director + ", producer=" + producer + ", releaseDate=" + releaseDate
				+ ", created=" + created + ", edited=" + edited + ", starships=" + starships + ", planets=" + planets
				+ ", peoples=" + peoples + ", vehicles=" + vehicles + "]";
	}

}
