package com.tema4.models;
// Generated 15 dic. 2020 17:38:37 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * People generated by hbm2java
 */
@Entity
@Table(name = "people")
public class People implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	private int codigo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeworld")
	private Planets planets;

	@Column(name = "name", length = 100)
	private String name;

	@Column(name = "birth_year", length = 100)
	private String birthYear;

	@Column(name = "eye_color", length = 100)
	private String eyeColor;

	@Column(name = "gender", length = 100)
	private String gender;

	@Column(name = "hair_color", length = 100)
	private String hairColor;

	@Column(name = "height", length = 100)
	private String height;

	@Column(name = "mass", length = 100)
	private String mass;

	@Column(name = "skin_color", length = 100)
	private String skinColor;

	@Column(name = "created", length = 100)
	private String created;

	@Column(name = "edited", length = 100)
	private String edited;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "starships_people", joinColumns = {
			@JoinColumn(name = "codigo_people", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_starship", nullable = false, updatable = false) })
	private Set<Starships> starships = new HashSet<Starships>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "species_people", joinColumns = {
			@JoinColumn(name = "codigo_people", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_specie", nullable = false, updatable = false) })
	private Set<Species> species = new HashSet<Species>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "vehicles_people", joinColumns = {
			@JoinColumn(name = "codigo_people", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_vehicle", nullable = false, updatable = false) })
	private Set<Vehicles> vehicles = new HashSet<Vehicles>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "films_people", joinColumns = {
			@JoinColumn(name = "codigo_people", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_film", nullable = false, updatable = false) })
	private Set<Films> films = new HashSet<Films>(0);

	public People() {
	}

	public People(int codigo) {
		this.codigo = codigo;
	}

	public People(int codigo, Planets planets, String name, String birthYear, String eyeColor, String gender,
			String hairColor, String height, String mass, String skinColor, String created, String edited,
			Set<Starships> starships, Set<Species> species, Set<Vehicles> vehicles, Set<Films> films) {
		this.codigo = codigo;
		this.planets = planets;
		this.name = name;
		this.birthYear = birthYear;
		this.eyeColor = eyeColor;
		this.gender = gender;
		this.hairColor = hairColor;
		this.height = height;
		this.mass = mass;
		this.skinColor = skinColor;
		this.created = created;
		this.edited = edited;
		this.starships = starships;
		this.species = species;
		this.vehicles = vehicles;
		this.films = films;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Planets getPlanets() {
		return planets;
	}

	public void setPlanets(Planets planets) {
		this.planets = planets;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBirthYear() {
		return birthYear;
	}

	public void setBirthYear(String birthYear) {
		this.birthYear = birthYear;
	}

	public String getEyeColor() {
		return eyeColor;
	}

	public void setEyeColor(String eyeColor) {
		this.eyeColor = eyeColor;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getHairColor() {
		return hairColor;
	}

	public void setHairColor(String hairColor) {
		this.hairColor = hairColor;
	}

	public String getHeight() {
		return height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	public String getMass() {
		return mass;
	}

	public void setMass(String mass) {
		this.mass = mass;
	}

	public String getSkinColor() {
		return skinColor;
	}

	public void setSkinColor(String skinColor) {
		this.skinColor = skinColor;
	}

	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	public String getEdited() {
		return edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	public Set<Starships> getStarships() {
		return starships;
	}

	public void setStarships(Set<Starships> starships) {
		this.starships = starships;
	}

	public Set<Species> getSpecies() {
		return species;
	}

	public void setSpecies(Set<Species> species) {
		this.species = species;
	}

	public Set<Vehicles> getVehicles() {
		return vehicles;
	}

	public void setVehicles(Set<Vehicles> vehicles) {
		this.vehicles = vehicles;
	}

	public Set<Films> getFilms() {
		return films;
	}

	public void setFilms(Set<Films> films) {
		this.films = films;
	}

	@Override
	public String toString() {
		return "People [codigo=" + codigo + ", planets=" + planets + ", name=" + name + ", birthYear=" + birthYear
				+ ", eyeColor=" + eyeColor + ", gender=" + gender + ", hairColor=" + hairColor + ", height=" + height
				+ ", mass=" + mass + ", skinColor=" + skinColor + ", created=" + created + ", edited=" + edited
				+ ", starships=" + starships + ", species=" + species + ", vehicles=" + vehicles + ", films=" + films
				+ "]";
	}
}
