package com.tema4.models;
// Generated 15 dic. 2020 17:38:37 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Planets generated by hbm2java
 */
@Entity
@Table(name = "planets")
public class Planets implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	private int codigo;

	@Column(name = "name", length = 100)
	private String name;

	@Column(name = "diameter", length = 100)
	private String diameter;

	@Column(name = "rotation_period", length = 100)
	private String rotationPeriod;

	@Column(name = "orbital_period", length = 100)
	private String orbitalPeriod;

	@Column(name = "gravity", length = 100)
	private String gravity;

	@Column(name = "population", length = 100)
	private String population;

	@Column(name = "climate", length = 100)
	private String climate;

	@Column(name = "terrain", length = 100)
	private String terrain;

	@Column(name = "surface_water", length = 100)
	private String surfaceWater;

	@Column(name = "created", length = 100)
	private String created;

	@Column(name = "edited", length = 100)
	private String edited;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planets")
	private Set<Species> specieses = new HashSet<Species>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planets")
	private Set<People> peoples = new HashSet<People>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "films_planets", joinColumns = {
			@JoinColumn(name = "codigo_planet", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_film", nullable = false, updatable = false) })
	private Set<Films> filmses = new HashSet<Films>(0);

	public Planets() {
	}

	public Planets(int codigo) {
		this.codigo = codigo;
	}

	public Planets(int codigo, String name, String diameter, String rotationPeriod, String orbitalPeriod,
			String gravity, String population, String climate, String terrain, String surfaceWater, String created,
			String edited, Set<Species> specieses, Set<People> peoples, Set<Films> filmses) {
		this.codigo = codigo;
		this.name = name;
		this.diameter = diameter;
		this.rotationPeriod = rotationPeriod;
		this.orbitalPeriod = orbitalPeriod;
		this.gravity = gravity;
		this.population = population;
		this.climate = climate;
		this.terrain = terrain;
		this.surfaceWater = surfaceWater;
		this.created = created;
		this.edited = edited;
		this.specieses = specieses;
		this.peoples = peoples;
		this.filmses = filmses;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDiameter() {
		return diameter;
	}

	public void setDiameter(String diameter) {
		this.diameter = diameter;
	}

	public String getRotationPeriod() {
		return rotationPeriod;
	}

	public void setRotationPeriod(String rotationPeriod) {
		this.rotationPeriod = rotationPeriod;
	}

	public String getOrbitalPeriod() {
		return orbitalPeriod;
	}

	public void setOrbitalPeriod(String orbitalPeriod) {
		this.orbitalPeriod = orbitalPeriod;
	}

	public String getGravity() {
		return gravity;
	}

	public void setGravity(String gravity) {
		this.gravity = gravity;
	}

	public String getPopulation() {
		return population;
	}

	public void setPopulation(String population) {
		this.population = population;
	}

	public String getClimate() {
		return climate;
	}

	public void setClimate(String climate) {
		this.climate = climate;
	}

	public String getTerrain() {
		return terrain;
	}

	public void setTerrain(String terrain) {
		this.terrain = terrain;
	}

	public String getSurfaceWater() {
		return surfaceWater;
	}

	public void setSurfaceWater(String surfaceWater) {
		this.surfaceWater = surfaceWater;
	}

	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	public String getEdited() {
		return edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	public Set<Species> getSpecieses() {
		return specieses;
	}

	public void setSpecieses(Set<Species> specieses) {
		this.specieses = specieses;
	}

	public Set<People> getPeoples() {
		return peoples;
	}

	public void setPeoples(Set<People> peoples) {
		this.peoples = peoples;
	}

	public Set<Films> getFilmses() {
		return filmses;
	}

	public void setFilmses(Set<Films> filmses) {
		this.filmses = filmses;
	}

	@Override
	public String toString() {
		return "Planets [codigo=" + codigo + ", name=" + name + ", diameter=" + diameter + ", rotationPeriod="
				+ rotationPeriod + ", orbitalPeriod=" + orbitalPeriod + ", gravity=" + gravity + ", population="
				+ population + ", climate=" + climate + ", terrain=" + terrain + ", surfaceWater=" + surfaceWater
				+ ", created=" + created + ", edited=" + edited + ", specieses=" + specieses + ", peoples=" + peoples
				+ ", filmses=" + filmses + "]";
	}

}
