package com.tema4.models;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Species generated by hbm2java
 */
@Entity
@Table(name = "species")
public class Species implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigo;
	private Planets planets;
	private String name;
	private String classification;
	private String designation;
	private String averageHeight;
	private String averageLifespan;
	private String eyeColors;
	private String hairColors;
	private String skinColors;
	private String language;
	private String created;
	private String edited;
	private Set<People> peoples = new HashSet<People>(0);

	public Species() {
	}

	public Species(int codigo) {
		this.codigo = codigo;
	}

	public Species(int codigo, Planets planets, String name, String classification, String designation,
			String averageHeight, String averageLifespan, String eyeColors, String hairColors, String skinColors,
			String language, String created, String edited, Set<People> peoples) {
		this.codigo = codigo;
		this.planets = planets;
		this.name = name;
		this.classification = classification;
		this.designation = designation;
		this.averageHeight = averageHeight;
		this.averageLifespan = averageLifespan;
		this.eyeColors = eyeColors;
		this.hairColors = hairColors;
		this.skinColors = skinColors;
		this.language = language;
		this.created = created;
		this.edited = edited;
		this.peoples = peoples;
	}

	@Id
	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeworld")
	public Planets getPlanets() {
		return this.planets;
	}

	public void setPlanets(Planets planets) {
		this.planets = planets;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "classification", length = 100)
	public String getClassification() {
		return this.classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	@Column(name = "designation", length = 100)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "average_height", length = 100)
	public String getAverageHeight() {
		return this.averageHeight;
	}

	public void setAverageHeight(String averageHeight) {
		this.averageHeight = averageHeight;
	}

	@Column(name = "average_lifespan", length = 100)
	public String getAverageLifespan() {
		return this.averageLifespan;
	}

	public void setAverageLifespan(String averageLifespan) {
		this.averageLifespan = averageLifespan;
	}

	@Column(name = "eye_colors", length = 100)
	public String getEyeColors() {
		return this.eyeColors;
	}

	public void setEyeColors(String eyeColors) {
		this.eyeColors = eyeColors;
	}

	@Column(name = "hair_colors", length = 100)
	public String getHairColors() {
		return this.hairColors;
	}

	public void setHairColors(String hairColors) {
		this.hairColors = hairColors;
	}

	@Column(name = "skin_colors", length = 100)
	public String getSkinColors() {
		return this.skinColors;
	}

	public void setSkinColors(String skinColors) {
		this.skinColors = skinColors;
	}

	@Column(name = "language", length = 100)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "created", length = 100)
	public String getCreated() {
		return this.created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Column(name = "edited", length = 100)
	public String getEdited() {
		return this.edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	@ManyToMany(fetch = FetchType.LAZY, targetEntity = People.class, cascade = CascadeType.ALL)
	@JoinTable(name = "species_people", joinColumns = {
			@JoinColumn(name = "codigo_specie", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_people", nullable = false, updatable = false) })
	public Set<People> getPeoples() {
		return this.peoples;
	}

	public void setPeoples(Set<People> peoples) {
		this.peoples = peoples;
	}

	public void imprimeRegistro() {
		StringBuilder sb = new StringBuilder();
		int codigo = getCodigo();
		sb.append(String.format("%-8s", codigo));
		String name = getName().trim().length() > 15 ? getName().substring(1, 15) + "..." : getName();
		sb.append(String.format("%-20s", name));
		String designacion = getDesignation();
		sb.append(String.format("%-20s", designacion));
		String alturaPromedio = getAverageHeight().equalsIgnoreCase("n/a")
				|| getAverageHeight().equalsIgnoreCase("unknown") ? "desconocida" : getAverageHeight();
		sb.append(String.format("%-20s", alturaPromedio));
		String esperanzaVida = getAverageLifespan().equalsIgnoreCase("unknown") ? "desconocida" : getAverageLifespan();
		sb.append(String.format("%-20s", esperanzaVida));
		String lenguaje = getLanguage().equalsIgnoreCase("n/a") ? "desconocido" : getLanguage();
		sb.append(String.format("%-20s", lenguaje));
		String mundo = getPlanets() == null ? "desconocido" : getPlanets().getName();
		sb.append(String.format("%-20s", mundo));
		String ojos = getEyeColors().equalsIgnoreCase("n/a") || getEyeColors().equalsIgnoreCase("unknown")
				|| getEyeColors().equalsIgnoreCase("none") ? "desconocido" : getEyeColors();
		sb.append(String.format("%-50s", ojos));
		String pelo = getHairColors().equalsIgnoreCase("n/a") || getHairColors().equalsIgnoreCase("unknown")
				|| getHairColors().equalsIgnoreCase("none") ? "desconocido" : getHairColors();
		sb.append(String.format("%-50s", pelo));
		String piel = getSkinColors().equalsIgnoreCase("n/a") || getSkinColors().equalsIgnoreCase("unknown")
				|| getSkinColors().equalsIgnoreCase("none") ? "desconocido" : getSkinColors();
		sb.append(String.format("%-50s", piel));
		String creado = getCreated();
		sb.append(String.format("%-40s", creado));
		String editado = getCreated();
		sb.append(String.format("%-40s", editado));
		System.out.println(sb.toString());
	}

	public void imprimeRegistroDetallado() {
		StringBuilder sb = new StringBuilder();
		int codigo = getCodigo();
		sb.append(String.format("%-50s", "Código: " + codigo));
		String name = getName();
		sb.append(String.format("%-50s", "Nombre de la especie: " + name));
		String designacion = getDesignation();
		sb.append(String.format("%-50s", "Designación: " + designacion) + " \n");
		sb.append("Carácteristicas Físicas\n");
		String alturaPromedio = getAverageHeight().equalsIgnoreCase("n/a")
				|| getAverageHeight().equalsIgnoreCase("unknown") ? "desconocida" : getAverageHeight();
		sb.append(String.format("%-50s", "Altura promedio: " + alturaPromedio));
		String esperanzaVida = getAverageLifespan().equalsIgnoreCase("unknown") ? "desconocida" : getAverageLifespan();
		sb.append(String.format("%-50s", "Esperanza de vida: " + esperanzaVida));

		String lenguaje = getLanguage().equalsIgnoreCase("n/a") ? "desconocido" : getLanguage();
		sb.append(String.format("%-50s", "Lenguaje: " + lenguaje));
		sb.append("\n");

		String mundo = getPlanets() == null ? "desconocido" : getPlanets().getName();
		sb.append(String.format("%-50s", "Mundo: " + mundo));

		sb.append("\n");

		String ojos = getEyeColors().equalsIgnoreCase("n/a") || getEyeColors().equalsIgnoreCase("unknown")
				? "desconocido"
				: getEyeColors();
		sb.append(String.format("%-50s", "Color de ojos: " + ojos));
		sb.append("\n");

		String pelo = getHairColors().equalsIgnoreCase("n/a") || getHairColors().equalsIgnoreCase("unknown")
				? "desconocido"
				: getHairColors();

		sb.append(String.format("%-50s", "Color de pelo: " + pelo));
		sb.append("\n");

		String piel = getSkinColors().equalsIgnoreCase("n/a") || getSkinColors().equalsIgnoreCase("unknown")
				? "desconocido"
				: getSkinColors();

		sb.append(String.format("%-50s", "Color de piel: " + piel));
		sb.append("\n----------------------------------------------\n");
		String creado = getCreated();
		sb.append(String.format("%-50s", "Creado: " + creado));
		sb.append("\n");
		String editado = getCreated();
		sb.append(String.format("%-50s", "Editado: " + editado));

		System.out.println(sb.toString());
	}

}
