package com.tema4.models;
// Generated 15 dic. 2020 17:38:37 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Species generated by hbm2java
 */
@Entity
@Table(name = "species")
public class Species implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	private int codigo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "homeworld")
	private Planets planets;

	@Column(name = "name", length = 100)
	private String name;

	@Column(name = "classification", length = 100)
	private String classification;

	@Column(name = "designation", length = 100)
	private String designation;

	@Column(name = "average_height", length = 100)
	private String averageHeight;

	@Column(name = "average_lifespan", length = 100)
	private String averageLifespan;

	@Column(name = "eye_colors", length = 100)
	private String eyeColors;

	@Column(name = "hair_colors", length = 100)
	private String hairColors;

	@Column(name = "skin_colors", length = 100)
	private String skinColors;

	@Column(name = "language", length = 100)
	private String language;

	@Column(name = "created", length = 100)
	private String created;

	@Column(name = "edited", length = 100)
	private String edited;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "species_people", joinColumns = {
			@JoinColumn(name = "codigo_specie", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_people", nullable = false, updatable = false) })
	private Set<People> peoples = new HashSet<People>(0);

	public Species() {
	}

	public Species(int codigo) {
		this.codigo = codigo;
	}

	public Species(int codigo, Planets planets, String name, String classification, String designation,
			String averageHeight, String averageLifespan, String eyeColors, String hairColors, String skinColors,
			String language, String created, String edited, Set<People> peoples) {
		this.codigo = codigo;
		this.planets = planets;
		this.name = name;
		this.classification = classification;
		this.designation = designation;
		this.averageHeight = averageHeight;
		this.averageLifespan = averageLifespan;
		this.eyeColors = eyeColors;
		this.hairColors = hairColors;
		this.skinColors = skinColors;
		this.language = language;
		this.created = created;
		this.edited = edited;
		this.peoples = peoples;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Planets getPlanets() {
		return planets;
	}

	public void setPlanets(Planets planets) {
		this.planets = planets;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClassification() {
		return classification;
	}

	public void setClassification(String classification) {
		this.classification = classification;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getAverageHeight() {
		return averageHeight;
	}

	public void setAverageHeight(String averageHeight) {
		this.averageHeight = averageHeight;
	}

	public String getAverageLifespan() {
		return averageLifespan;
	}

	public void setAverageLifespan(String averageLifespan) {
		this.averageLifespan = averageLifespan;
	}

	public String getEyeColors() {
		return eyeColors;
	}

	public void setEyeColors(String eyeColors) {
		this.eyeColors = eyeColors;
	}

	public String getHairColors() {
		return hairColors;
	}

	public void setHairColors(String hairColors) {
		this.hairColors = hairColors;
	}

	public String getSkinColors() {
		return skinColors;
	}

	public void setSkinColors(String skinColors) {
		this.skinColors = skinColors;
	}

	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	public String getEdited() {
		return edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	public Set<People> getPeoples() {
		return peoples;
	}

	public void setPeoples(Set<People> peoples) {
		this.peoples = peoples;
	}

	@Override
	public String toString() {
		return "Species [codigo=" + codigo + ", planets=" + planets + ", name=" + name + ", classification="
				+ classification + ", designation=" + designation + ", averageHeight=" + averageHeight
				+ ", averageLifespan=" + averageLifespan + ", eyeColors=" + eyeColors + ", hairColors=" + hairColors
				+ ", skinColors=" + skinColors + ", language=" + language + ", created=" + created + ", edited="
				+ edited + ", peoples=" + peoples + "]";
	}

}
