package com.tema4.models;
// Generated 15 dic. 2020 17:38:37 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Starships generated by hbm2java
 */
@Entity
@Table(name = "starships")
public class Starships implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	private int codigo;

	@Column(name = "name", length = 100)
	private String name;

	@Column(name = "model", length = 100)
	private String model;

	@Column(name = "starship_class", length = 100)
	private String starshipClass;

	@Column(name = "manufacturer", length = 100)
	private String manufacturer;

	@Column(name = "cost_in_credits", length = 100)
	private String costInCredits;

	@Column(name = "length", length = 100)
	private String length;

	@Column(name = "crew", length = 100)
	private String crew;

	@Column(name = "passengers", length = 100)
	private String passengers;

	@Column(name = "max_atmosphering_speed", length = 100)
	private String maxAtmospheringSpeed;

	@Column(name = "hyperdrive_rating", length = 100)
	private String hyperdriveRating;

	@Column(name = "MGLT", length = 100)
	private String mglt;

	@Column(name = "cargo_capacity", length = 100)
	private String cargoCapacity;

	@Column(name = "consumables ", length = 100)
	private String consumables;

	@Column(name = "created", length = 100)
	private String created;

	@Column(name = "edited", length = 100)
	private String edited;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "starships_films", joinColumns = {
			@JoinColumn(name = "codigo_starship", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_film", nullable = false, updatable = false) })
	private Set<Films> films = new HashSet<Films>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "starships_people", joinColumns = {
			@JoinColumn(name = "codigo_starship", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_people", nullable = false, updatable = false) })
	private Set<People> peoples = new HashSet<People>(0);

	public Starships() {
	}

	public Starships(int codigo) {
		this.codigo = codigo;
	}

	public Starships(int codigo, String name, String model, String starshipClass, String manufacturer,
			String costInCredits, String length, String crew, String passengers, String maxAtmospheringSpeed,
			String hyperdriveRating, String mglt, String cargoCapacity, String consumables, String created,
			String edited, Set<Films> films, Set<People> peoples) {
		super();
		this.codigo = codigo;
		this.name = name;
		this.model = model;
		this.starshipClass = starshipClass;
		this.manufacturer = manufacturer;
		this.costInCredits = costInCredits;
		this.length = length;
		this.crew = crew;
		this.passengers = passengers;
		this.maxAtmospheringSpeed = maxAtmospheringSpeed;
		this.hyperdriveRating = hyperdriveRating;
		this.mglt = mglt;
		this.cargoCapacity = cargoCapacity;
		this.consumables = consumables;
		this.created = created;
		this.edited = edited;
		this.films = films;
		this.peoples = peoples;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getStarshipClass() {
		return starshipClass;
	}

	public void setStarshipClass(String starshipClass) {
		this.starshipClass = starshipClass;
	}

	public String getManufacturer() {
		return manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getCostInCredits() {
		return costInCredits;
	}

	public void setCostInCredits(String costInCredits) {
		this.costInCredits = costInCredits;
	}

	public String getLength() {
		return length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	public String getCrew() {
		return crew;
	}

	public void setCrew(String crew) {
		this.crew = crew;
	}

	public String getPassengers() {
		return passengers;
	}

	public void setPassengers(String passengers) {
		this.passengers = passengers;
	}

	public String getMaxAtmospheringSpeed() {
		return maxAtmospheringSpeed;
	}

	public void setMaxAtmospheringSpeed(String maxAtmospheringSpeed) {
		this.maxAtmospheringSpeed = maxAtmospheringSpeed;
	}

	public String getHyperdriveRating() {
		return hyperdriveRating;
	}

	public void setHyperdriveRating(String hyperdriveRating) {
		this.hyperdriveRating = hyperdriveRating;
	}

	public String getMglt() {
		return mglt;
	}

	public void setMglt(String mglt) {
		this.mglt = mglt;
	}

	public String getCargoCapacity() {
		return cargoCapacity;
	}

	public void setCargoCapacity(String cargoCapacity) {
		this.cargoCapacity = cargoCapacity;
	}

	public String getConsumables() {
		return consumables;
	}

	public void setConsumables(String consumables) {
		this.consumables = consumables;
	}

	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	public String getEdited() {
		return edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	public Set<Films> getFilms() {
		return films;
	}

	public void setFilms(Set<Films> films) {
		this.films = films;
	}

	public Set<People> getPeoples() {
		return peoples;
	}

	public void setPeoples(Set<People> peoples) {
		this.peoples = peoples;
	}

	@Override
	public String toString() {
		return "Starships [codigo=" + codigo + ", name=" + name + ", model=" + model + ", starshipClass="
				+ starshipClass + ", manufacturer=" + manufacturer + ", costInCredits=" + costInCredits + ", length="
				+ length + ", crew=" + crew + ", passengers=" + passengers + ", maxAtmospheringSpeed="
				+ maxAtmospheringSpeed + ", hyperdriveRating=" + hyperdriveRating + ", mglt=" + mglt
				+ ", cargoCapacity=" + cargoCapacity + ", consumables=" + consumables + ", created=" + created
				+ ", edited=" + edited + ", films=" + films + ", peoples=" + peoples + "]";
	}

}
