package com.tema4.models;
// Generated 15 dic. 2020 17:38:37 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Vehicles generated by hbm2java
 */
@Entity
@Table(name = "vehicles")
public class Vehicles implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "codigo", unique = true, nullable = false)
	private int codigo;

	@Column(name = "name", length = 100)
	private String name;

	@Column(name = "model", length = 100)
	private String model;

	@Column(name = "vehicle_class", length = 100)
	private String vehicleClass;

	@Column(name = "manufacturer", length = 100)
	private String manufacturer;

	@Column(name = "length", length = 100)
	private String length;

	@Column(name = "cost_in_credits", length = 100)
	private String costInCredits;

	@Column(name = "crew", length = 100)
	private String crew;

	@Column(name = "passengers", length = 100)
	private String passengers;

	@Column(name = "max_atmosphering_speed", length = 100)
	private String maxAtmospheringSpeed;

	@Column(name = "cargo_capacity", length = 100)
	private String cargoCapacity;

	@Column(name = "consumables", length = 100)
	private String consumables;

	@Column(name = "created", length = 100)
	private String created;

	@Column(name = "edited", length = 100)
	private String edited;

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "vehicles_people", joinColumns = {
			@JoinColumn(name = "codigo_vehicle", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_people", nullable = false, updatable = false) })
	private Set<People> peoples = new HashSet<People>(0);

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "vehicles_films", joinColumns = {
			@JoinColumn(name = "codigo_vehicle", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "codigo_film", nullable = false, updatable = false) })
	private Set<Films> films = new HashSet<Films>(0);

	public Vehicles() {
	}

	public Vehicles(int codigo) {
		this.codigo = codigo;
	}

	public Vehicles(int codigo, String name, String model, String vehicleClass, String manufacturer, String length,
			String costInCredits, String crew, String passengers, String maxAtmospheringSpeed, String cargoCapacity,
			String consumables, String created, String edited, Set<People> peoples, Set<Films> films) {
		super();
		this.codigo = codigo;
		this.name = name;
		this.model = model;
		this.vehicleClass = vehicleClass;
		this.manufacturer = manufacturer;
		this.length = length;
		this.costInCredits = costInCredits;
		this.crew = crew;
		this.passengers = passengers;
		this.maxAtmospheringSpeed = maxAtmospheringSpeed;
		this.cargoCapacity = cargoCapacity;
		this.consumables = consumables;
		this.created = created;
		this.edited = edited;
		this.peoples = peoples;
		this.films = films;
	}

	public int getCodigo() {
		return codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getVehicleClass() {
		return vehicleClass;
	}

	public void setVehicleClass(String vehicleClass) {
		this.vehicleClass = vehicleClass;
	}

	public String getManufacturer() {
		return manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getLength() {
		return length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	public String getCostInCredits() {
		return costInCredits;
	}

	public void setCostInCredits(String costInCredits) {
		this.costInCredits = costInCredits;
	}

	public String getCrew() {
		return crew;
	}

	public void setCrew(String crew) {
		this.crew = crew;
	}

	public String getPassengers() {
		return passengers;
	}

	public void setPassengers(String passengers) {
		this.passengers = passengers;
	}

	public String getMaxAtmospheringSpeed() {
		return maxAtmospheringSpeed;
	}

	public void setMaxAtmospheringSpeed(String maxAtmospheringSpeed) {
		this.maxAtmospheringSpeed = maxAtmospheringSpeed;
	}

	public String getCargoCapacity() {
		return cargoCapacity;
	}

	public void setCargoCapacity(String cargoCapacity) {
		this.cargoCapacity = cargoCapacity;
	}

	public String getConsumables() {
		return consumables;
	}

	public void setConsumables(String consumables) {
		this.consumables = consumables;
	}

	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	public String getEdited() {
		return edited;
	}

	public void setEdited(String edited) {
		this.edited = edited;
	}

	public Set<People> getPeoples() {
		return peoples;
	}

	public void setPeoples(Set<People> peoples) {
		this.peoples = peoples;
	}

	public Set<Films> getFilms() {
		return films;
	}

	public void setFilms(Set<Films> films) {
		this.films = films;
	}

	@Override
	public String toString() {
		return "Vehicles [codigo=" + codigo + ", name=" + name + ", model=" + model + ", vehicleClass=" + vehicleClass
				+ ", manufacturer=" + manufacturer + ", length=" + length + ", costInCredits=" + costInCredits
				+ ", crew=" + crew + ", passengers=" + passengers + ", maxAtmospheringSpeed=" + maxAtmospheringSpeed
				+ ", cargoCapacity=" + cargoCapacity + ", consumables=" + consumables + ", created=" + created
				+ ", edited=" + edited + ", peoples=" + peoples + ", films=" + films + "]";
	}

}
